<?php

namespace ContainerAvAUriy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashStringService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\HashString' shared autowired service.
     *
     * @return \App\Command\HashString
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/HashString.php';

        $container->privates['App\\Command\\HashString'] = $instance = new \App\Command\HashString('', 0, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('avato:test');

        return $instance;
    }
}
