<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_lucky_number' => [['max'], ['_controller' => 'App\\Controller\\HashStringController::process'], [], [['variable', '/', '[^/]++', 'max', true], ['text', '/lucky/number']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'api_post_show' => [['inicial'], ['_controller' => 'App\\Controller\\HashStringController::hash_string'], [], [['text', '/'], ['variable', '/', '[^/]++', 'inicial', true], ['text', '/hash']], [], []],
    'api_post_api' => [['inicial', 'json'], ['_controller' => 'App\\Controller\\HashStringController::hash_string'], [], [['variable', '/', '[^/]++', 'json', true], ['variable', '/', '[^/]++', 'inicial', true], ['text', '/api']], [], []],
];
